# web/api/schemas/__init__.py
from web.api.schemas.request import (
    DiagnoseRequest,
    DiagnoseResponse,
    DiagnoseStatusResponse,
    OpticsRequest,
    SearchRequest,
    SearchResultItem,
    SearchResponse,
    ResetLanRequest,
    ClearBipRequest,
    RemotePingRequest,
    ActionResponse,
    HistoryQueryParams,
    HistoryItem,
    HistoryResponse,
    PortSummaryRequest,
    OntSummaryItem,
    PortSummaryResponse,
    OLTInfo,
    OLTsResponse,
    HealthResponse,
)

from web.api.schemas.response import (
    DiagnosisReportResponse,
    OpticsResponse,
    PortSummaryResponse as PortSummaryResponseModel,
    PortSummaryItemResponse,
    HistoryItemResponse,
    HistoryResponse as HistoryResponseModel,
    OLTResponse,
    OLTsResponse as OLTsResponseModel,
    HealthResponse as HealthResponseModel,
    SuccessResponse,
    ErrorResponse,
)

from web.api.schemas.ws import (
    PortSummarySnapshot,
    PortSummaryUpdate,
    PortSummaryError,
    OpticsData,
    OpticsError,
    DiagnosisProgress,
    DiagnosisComplete,
    DiagnosisError,
    DiagnosisHistory,
    WSMessage,
)

__all__ = [
    # Request
    "DiagnoseRequest",
    "DiagnoseResponse",
    "DiagnoseStatusResponse",
    "OpticsRequest",
    "SearchRequest",
    "SearchResultItem",
    "SearchResponse",
    "ResetLanRequest",
    "ClearBipRequest",
    "RemotePingRequest",
    "ActionResponse",
    "HistoryQueryParams",
    "HistoryItem",
    "HistoryResponse",
    "PortSummaryRequest",
    "OntSummaryItem",
    "PortSummaryResponse",
    "OLTInfo",
    "OLTsResponse",
    "HealthResponse",
    # Response
    "DiagnosisReportResponse",
    "OpticsResponse",
    "PortSummaryResponseModel",
    "PortSummaryItemResponse",
    "HistoryItemResponse",
    "HistoryResponseModel",
    "OLTResponse",
    "OLTsResponseModel",
    "HealthResponseModel",
    "SuccessResponse",
    "ErrorResponse",
    # WebSocket
    "PortSummarySnapshot",
    "PortSummaryUpdate",
    "PortSummaryError",
    "OpticsData",
    "OpticsError",
    "DiagnosisProgress",
    "DiagnosisComplete",
    "DiagnosisError",
    "DiagnosisHistory",
    "WSMessage",
]